[basicConfig]
#node manager name
name = "node1"
#blockchain client RPC URL
bcClntRpcUrl = "http://127.0.0.1:22000"
consensus = "clique"
clientType = "besu"
nodeManagerConfigFile = "./test/shell/nm1.toml"
upcheckPollingInterval = 1
inactivityTime = 60

proxies = [
    { name = "besu-rpc", type = "http", proxyAddr = "localhost:9091", upstreamAddr = "http://localhost:22000", proxyPaths = ["/"], readTimeout = 15, writeTimeout = 15 },
]

#rpc server details of node manager
[basicConfig.server]
# The interface + port the application should bind to
rpcAddr = "localhost:8081"
rpcCorsList = ["*"]
rpcvHosts = ["*"]

[basicConfig.bcClntProcess]
name = "bcclnt"
controlType = "shell"
startCommand = ["bash", "/Users/saiv/temp/besu-network/clique-network/node-1/start-node.sh", "1"]
stopCommand = ["bash", "/Users/saiv/temp/besu-network/clique-network/node-1/stop-node.sh", "22000"]
