#node manager name
name = "node3"

#geth RPC URL
gethRpcUrl = "http://localhost:22002"

#proxy address
proxyAddr = ":9093"

#geth inactivity timeout
gethInactivityTime = 1000000

#geth's http/ws services that need to be exposed as proxy services
proxies = [
    { name = "rpc", path = "rpc", type = "http", destUrl = "http://localhost:22002" },
    { name = "ws", path = "ws", type = "ws", destUrl = ":23002" },
    { name = "tessera", path = "tessera", type = "http", destUrl = "http://localhost:9003" }
]

nodeManagers = [
    { name = "node1", tesseraKey = "oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8=", rpcUrl = "http://localhost:8081" },
    { name = "node2", tesseraKey = "QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc=", rpcUrl = "http://localhost:8082" },
    { name = "node3", tesseraKey = "1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg=", rpcUrl = "http://localhost:8083" },
    { name = "node4", tesseraKey = "1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg=", rpcUrl = "http://localhost:8084" }
]

#rpc server details of node manager
[server]
# The interface + port the application should bind to
rpcAddr = "localhost:8083"
rpcCorsList = ["*"]
rpcvHosts = ["*"]

#geth's process control config
[gethProcess]
controlType = "shell"
stopCommand = ["bash", "/Users/maniam/tmp/quorum-examples/examples/7nodes/stopNode.sh", "22002"]
startCommand = ["bash", "/Users/maniam/tmp/quorum-examples/examples/7nodes/startNode.sh", "3"]

	