[[peers]]
name = "node1"
privacyManagerKey = "BULeR8JyUWhiuuCMU/HLA0Q5pzkYT+cHII3ZKBey3Bo="
rpcUrl = "http://host.docker.internal:8081"

[[peers]]
name = "node2"
privacyManagerKey = "QfeDAys9MPDs2XHExtc84jKGHxZg/aj52DTh0vtA3Xc="
rpcUrl = "http://host.docker.internal:8082"

[[peers]]
name = "node3"
privacyManagerKey = "1iTZde/ndBHvzhcl7V68x44Vx7pl8nwx9LqnM/AfJUg="
rpcUrl = "http://host.docker.internal:8083"

[[peers]]
name = "node4"
privacyManagerKey = "oNspPPgszVUFw0qmGFfWwh1uxVUXgvBxleXORHj07g8="
rpcUrl = "http://host.docker.internal:8084"

[[peers]]
name = "node5"
privacyManagerKey = "R56gy4dn24YOjwyesTczYa8m5xhP6hF2uTMCju/1xkY="
rpcUrl = "http://host.docker.internal:8085"

[[peers]]
name = "node6"
privacyManagerKey = "UfNSeSGySeKg11DVNEnqrUtxYRVor4+CvluI8tVv62Y="
rpcUrl = "http://host.docker.internal:8086"

[[peers]]
name = "node7"
privacyManagerKey = "ROAZBWtSacxXQrOe3FGAqJDyJjFePR5ce4TSIzmJ0Bc="
rpcUrl = "http://host.docker.internal:8087"